# Generated by Django 4.2 on 2023-09-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatLLM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='owner',
        ),
    ]
