# Generated by Django 4.2 on 2023-09-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatLLM', '0002_remove_conversation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time_sent',
        ),
    ]
